- name: postgres instance - ensure all are internal/external
  fail:
    msg: All database must either be internal or external. Mix-n-match is not supported
  when:
    - settings.internal != internal
  tags:
    - install
    - uninstall
    - update

- name: postgres - internal default
  overlay_facts:
    cadence_name: "{{ V4_CFG_CADENCE_NAME }}"
    cadence_number: "{{ V4_CFG_CADENCE_VERSION }}"
    existing: "{{ vdm_overlays }}"
    add:
      - { resources: "overlays/internal-postgres" }
  when: 
    - settings.internal
    - role == "default"
  tags:
    - install
    - uninstall
    - update

- name: postgres - internal folder check
  stat:
    path: "{{ DEPLOY_DIR }}/sas-bases/overlays/internal-postgres/{{ role }}"
  register: result
  when: settings.internal
  tags:
    - install
    - uninstall
    - update

- name: postgres - internal cds
  overlay_facts:
    cadence_name: "{{ V4_CFG_CADENCE_NAME }}"
    cadence_number: "{{ V4_CFG_CADENCE_VERSION }}"
    existing: "{{ vdm_overlays }}"
    add:
      - { resources: "overlays/internal-postgres/{{ role }}" }
  when: 
    - settings.internal
    - result.stat.exists
  tags:
    - install
    - uninstall
    - update

- name: postgres instance - external post 2022.10
  block:
  - name: postgres instance - external copy postgres-user.env
    template:
      src: "postgres-user.env"
      dest: "{{ DEPLOY_DIR }}/site-config/postgres-{{ role }}-user.env"
      mode: "0660"
  - name: postgres instance - external copy secret generator template
    template:
      src: "{{ role_path }}/templates/generators/postgres-secrets.yaml"
      dest: "{{ role_path }}/templates/generators/postgres-{{ role }}-secrets.yaml"
      mode: "0660"
  - name: postgres instance - external copy dataserver transformer template
    template:
      src: "{{ role_path }}/templates/transformers/dataserver-transformer.yaml"
      dest: "{{ role_path }}/templates/transformers/{{ role }}-dataserver-transformer.yaml"
      mode: "0660"
  - name: postgres instance - external kustomization entries
    overlay_facts:
      cadence_name: "{{ V4_CFG_CADENCE_NAME }}"
      cadence_number: "{{ V4_CFG_CADENCE_VERSION }}"
      existing: "{{ vdm_overlays }}"
      add:
        - { transformers: "{{ role }}-dataserver-transformer.yaml", min: "2022.10", vdm: true}
        - { generators: "postgres-{{ role }}-secrets.yaml", min: "2022.10", vdm: true}
  when:
    - not settings.internal
    - V4_CFG_CADENCE_VERSION is version('2022.10', ">=") or V4_CFG_CADENCE_NAME|lower == "fast"
  tags:
    - install
    - uninstall
    - update

- block:
  - name: postgres instance - crd
    template:
      src: "{{ role_path }}/templates/resources/postgres-instance.yaml"
      dest: "{{ role_path }}/templates/resources/postgres-{{ role }}-instance.yaml"
      mode: "0660"
  - overlay_facts:
      cadence_name: "{{ V4_CFG_CADENCE_NAME }}"
      cadence_number: "{{ V4_CFG_CADENCE_VERSION }}"
      existing: "{{ vdm_overlays }}"
      add:
        - { resources: "postgres-{{ role }}-instance.yaml", vdm: true }
  when:
    - not settings.internal or ( settings.internal and role != "default" and not result.stat.exists )
    - V4_CFG_CADENCE_VERSION is version('2022.10', "<")
    - V4_CFG_CADENCE_NAME|lower != "fast"
  tags:
    - install
    - uninstall
    - update
