- name: postgres - internal
  overlay_facts:
    cadence_name: "{{ V4_CFG_CADENCE_NAME }}"
    cadence_number: "{{ V4_CFG_CADENCE_VERSION }}"
    existing: "{{ vdm_overlays }}"
    add:
      - { resources: "overlays/internal-postgres" }
      - { resources: "overlays/crunchydata" }
      - { transformers: "overlays/internal-postgres/internal-postgres-transformer.yaml" }
      - { transformers: "postgres-storage-transformer.yaml", vdm: true, max: "2020.1.3" }
      - { transformers: "postgres-storage-transformer.v2.yaml", vdm: true, min: "2020.1.3"}
  when: 
    - V4_CFG_POSTGRES_TYPE == 'internal'
  tags:
    - install
    - uninstall
    - upgrade

- name: postgres - external
  overlay_facts:
    cadence_name: "{{ V4_CFG_CADENCE_NAME }}"
    cadence_number: "{{ V4_CFG_CADENCE_VERSION }}"
    existing: "{{ vdm_overlays }}"
    add:
      - { transformers: "overlays/external-postgres/external-postgres-transformer.yaml" }
      - { generators: "postgres-sas-user.yaml", vdm: true }
      - { generators: "sas-go-config.yaml", vdm: true }
      - { generators: "sas-postgres-config.yaml", max: "2020.0.4", vdm: true }
      - { generators: "sas-postgres-config.v2.yaml", min: "2020.0.5", vdm: true }
  when: 
    - V4_CFG_POSTGRES_TYPE == 'external'
  tags:
    - install
    - uninstall
    - upgrade
