---
- name: storage - storageclass
  overlay_facts:
    cadence_name: "{{ V4_CFG_CADENCE_NAME }}"
    cadence_number: "{{ V4_CFG_CADENCE_VERSION }}"
    existing: "{{ vdm_overlays }}"
    add:
      - { transformers: "sas-storageclass.yaml", vdm: true, priority: 49 }
  tags:
    - install
    - uninstall
    - update

- name: storage - nfs
  overlay_facts:
    cadence_name: "{{ V4_CFG_CADENCE_NAME }}"
    cadence_number: "{{ V4_CFG_CADENCE_VERSION }}"
    existing: "{{ vdm_overlays }}"
    add:
      - { transformers: "cas-add-nfs-mount.yaml", vdm: true }
      - { transformers: "compute-server-add-nfs-mount.yaml", max: "2022.1.4", vdm: true }
      - { transformers: "compute-server-add-nfs-mount.v2.yaml", min: "2022.09", vdm: true }
      - { transformers: "launcher-service-add-nfs.yaml", max: "2022.1.4", vdm: true }
      - { transformers: "launcher-nfs-mount.yaml", min: "2022.09", vdm: true }
  when:
    - V4_CFG_RWX_FILESTORE_ENDPOINT is not none
    - V4_CFG_RWX_FILESTORE_PATH is not none
  tags:
    - install
    - uninstall
    - update
