{% set db = db_default_name_map[role] if role in db_default_name_map else settings.database|default(role, true) %}
apiVersion: webinfdsvr.sas.com/v1
kind: Pgcluster
metadata:
  name: {{ role }}
{% if role == "default" %}
  annotations:
    sas.com/default-database: "true"
{% endif %}
spec:
  internal: {{ settings.internal|bool|lower }}
  database: {{ db }}
{% if settings.internal|bool %}
  storage:
    storageclass: {{ V4_CFG_STORAGECLASS }}
{% else %}
  connection:
    host: {{ settings.fqdn }}
    port: {{ settings.server_port|default(5432, true) }}
    ssl: {{ settings.ssl_enforcement_enabled|bool|lower }}
  rolesecret: postgres-{{ role }}-user
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-{{ role }}-user
  labels:
    pg-cluster: "{{ role }}"
stringData:
  username: {{ settings.admin }}
  password: {{ settings.password }}
{% endif %}
